Hw02 express
Volodymyr-Bezyk/nodejs-rest-API pull request #1
Opened 2022-12-30 15:03 UTC by Volodymyr-Bezyk

Доброго дня.
Вітаю Вас із наступаючим новим роком!
Миру, достатку та здоров`я Вам у новому році!

2022-12-30 19:52 UTC, KhYulian commented on routes/api/contacts.js
> +    errorHandler(next, err, "Get request error");
тут просто викликайте nextта передавайте помилку. errorHandler виглядає надлишковим. Можна обійтись без нього і код буде чистішим

2022-12-30 19:53 UTC, KhYulian commented on routes/api/contacts.js
> +    if (!(name && email && phone))
if (!name || !email || !phone) - так було б краще. А ще краще застусувати тут Joi для валідації

2022-12-30 19:54 UTC, KhYulian requested changes
Потрібне доопрацювання

2022-12-30 20:10 UTC, Volodymyr-Bezyk commented on routes/api/contacts.js
> +    errorHandler(next, err, "Get request error");
+

2022-12-30 20:13 UTC, Volodymyr-Bezyk commented on routes/api/contacts.js
> +    if (!(name && email && phone))
Ок. Там по валідації було використано 2 варіанта.
Виправив, залишив тільки Joi.

2022-12-31 08:57 UTC, KhYulian approved these changes
Чудова робота 😎

2022-12-31 08:58 UTC, merged